services:
  backend:
    build: ./backend
    container_name: warehouse-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: warehouse-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
